import Layout from '../../components/layout'
import Container from '../../components/container'
import Head from 'next/head'

export default function TermsAndConditions() {
  return (
    <>
      <Layout>
        <Container>
          <div className="footer-pages">
            <h1 className="main-headline text-6xl font-bold mb-8 pt-10 mb-8">terms and conditions.</h1>
            <p>I Need Bike Parts provides for the sale of health supplements (“Service” or “Company Service”) via the Company website(s) offered from time to time at the URL https://ineedbikeparts.com  (collectively, the “Site,” or “Sites”). The Company Service is owned and operated by I Need Bike Parts, Inc. (“Company”, “we” or “us”). Your use of the Company Service is subject to the terms and conditions set forth in these Terms of Service (the “Terms of Service”). PLEASE READ THE TERMS OF SERVICE CAREFULLY. BY ACCESSING OR USING ANY PART OF THE COMPANY SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY ALL THE TERMS OF THE TERMS OF SERVICE. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, EXIT THIS PAGE AND DO NOT ACCESS OR USE THE COMPANY SERVICE. USE OF THE COMPANY SERVICE IS EXPRESSLY CONDITIONED UPON YOUR ACCEPTANCE OF THE TERMS OF SERVICE.</p>

            <h2>1. Updates to Terms of Service; Integration.</h2>
            <p>We may, in our sole discretion, modify the Terms of Service via email or by posting notice on any part of the Company Service. The “Last Updated” date at the top the Terms of Service indicates when the latest modifications were made to the Terms of Service. By continuing to access and use the Company Service you agree to any such modifications. Therefore, you are responsible for reviewing and should become familiar with any such modifications. You are encouraged to review this Terms of Service periodically and to check the “Last Updated” date at the top of the Terms of Service for the most recent version. In addition, when using services or features on the Company Service, you will be subject to any posted guidelines or policies applicable to such services or features that may be posted from time to time, including but not limited to the Privacy Policy as noted below. All such guidelines or policies are hereby incorporated by reference into these Terms of Service.</p>


            <h2>2. Translation.</h2>
            <p>We may translate these Terms of Service into other languages for your convenience. Nevertheless, the English version governs your relationship with Company, and any inconsistencies among the different versions will be resolved in favor of the English version.</p>


            <h2>3. Service Availability.</h2>
            <p>The Company Service may be modified, updated, interrupted, suspended or discontinued at any time without notice or liability. If the Company Service were discontinued at any time, all data would be deleted pursuant to the discontinuation process.</p>


            <h2>4. Privacy Policy.</h2>
            <p>Use of the Company Service is subject to the terms of our Privacy Policy which is hereby incorporated into and made part of these Terms of Service. Please carefully review our Privacy Policy. By using or accessing the Company Service, you agree to be bound by the terms of our Privacy Policy.</p>


            <h2>5. Age.</h2>
            <p>The Service is meant for those at least eighteen (18) years of age. Use of the Service by anyone under the age of eighteen (18) is a violation of the Terms of Service. You may not use the Service if you are a competitor of the Service, or if we have previously banned you from use of the Service or closed your account.</p>


            <h2>6. Intellectual Property.</h2>
            <p>You acknowledge that all materials on the Company Service, including, but not limited to, the Website design, Application design, graphics, text, sounds, pictures, and other files and the selection and arrangement thereof (collectively, “Materials”), are the property of Company and/or its licensors, and are subject to and protected by United States and Canada and international copyright and other intellectual property laws and rights. All rights to Materials not expressly granted in these Terms of Service are reserved to their respective copyright owners. Company authorizes you to view, download and/or print the Materials only for personal, non-commercial use, provided that you keep intact all copyright and other proprietary notices contained in the original Materials. Except as expressly authorized by the Terms of Service, you may not copy, reproduce, distribute, re-publish, download, perform, display, post, transmit, scrape, copy, exploit, create derivative works or otherwise use any of the Materials in any form or by any means, without the prior written authorization of Company or the respective copyright owner. In the absence of a written agreement, you may not modify or adapt the Materials in any way or otherwise use them for any public or commercial purposes. The trademarks, service marks, trade names, trade dress and logos (collectively, “Marks”) contained or described in the Company Service are the sole property of Company and/or its licensors and may not be copied, altered or otherwise used, in whole or in part, without the prior written authorization of Company and/or its licensors. Company reserves the right to enforce its intellectual property rights fully under the law.</p>

            <p>Your use of the Company Service is solely and exclusively under the limited license granted herein and you will not obtain any ownership interest therein through the Terms of Service or otherwise. All trademarks, service marks, trade names, domain names, slogans, logos, and other indicia of origin that appear on or in connection with any aspect of the Company Service are either the property of Company, its affiliates or licensors. Company retains the right to rescind and terminate the limited license granted hereunder at any point, for any reason. All rights not expressly granted herein by Company to you are fully reserved by Company, its advertisers and licensors.</p>

            <p>Some of the company and product names, logos, brands, and other trademarks featured or referred to within the Company Service may not be owned by us and are the property of their respective trademark holders. These trademark holders are not affiliated with, nor do they sponsor or endorse the Company Service.</p>


            <h2>7. Third Party Sites & Services.</h2>
            <p>Links provided via the Company Service to Third-Party websites and services are provided only as a convenience. If you use these links, you may leave the Company Service. Company does not control nor endorse any such Third-Party websites. You agree that the Company Parties, as defined below, will not be responsible or liable for any content, goods or services provided by such Third-Party websites or for your use or inability to use such Third-Party websites. You will use such links at your own risk.</p>

            <p>You are advised that other websites on the Internet, including Third-Party websites linked from the Company Service, might contain material or information: that some people may find offensive or inappropriate; that is inaccurate, untrue, misleading or deceptive; or that is defamatory, libelous, infringing of others’ rights or otherwise unlawful. Company expressly disclaims any responsibility for the content, legality, decency or accuracy of any information, and for any products and services, that appear on any Third-Party website or in advertisements or content that Third-Party websites may have in the Company Service.</p>

            <p>Your interactions with organizations and/or individuals and Third-Party companies found on or through the Company Service, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You agree and acknowledge that Company shall not under any circumstances be liable for any damages of any kind arising out of, or in connection with, or relating to, the products and services of a Thirty-Party.</p>


            <h2>8. Use of the Service.</h2>
            <p>You may be required to establish an account to use the Company Service and/or take advantage of certain features. The right to use the Service is personal to the user and user accounts are not transferable.</p>
            <p><b>8.1</b> You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all activities that occur under your account. Your account is meant to be private and you shall not share accounts for any reason. You agree to immediately notify us of any unauthorized use of your password or account or any other breach of security. You agree to be responsible for all charges resulting from the use of your account via the Company Service, including charges resulting from unauthorized use of your account.</p>
            <p><b>8.2</b> You may not impersonate someone else (e.g., adopt the identity of a celebrity or your next-door neighbor), create or use an account for anyone other than yourself, provide an email address other than your own, or create multiple accounts. If you use a pseudonym, take care to note that others may still be able to identify you if, for example, you include identifying information in your reviews, use the same account information on other sites, or allow other sites to share information about you with the Company Service.</p>
            <p><b>8.3</b> You agree to use the Company Service only for lawful purposes and that you are responsible for your use of and communications and content you may post via the Company Service. You agree not to post or transmit any unlawful, infringing, threatening, harassing, defamatory, vulgar, obscene, profane, indecent, offensive, hateful or otherwise objectionable material of any kind, including any material that encourages criminal conduct or conduct that would give rise to civil liability, infringes upon others’ intellectual property rights, impersonates any individual or entity, or otherwise violates any applicable law. You agree not to solicit personal information from minors. You agree not to use the Company Service in any manner that interferes with its normal operation or with any other user’s use of the Company Service.</p>
            <p><b>8.4</b> You may not do any of the following while accessing or using the Company Service:</p>
            <ul>
              <li>access, tamper with, or use non-public areas of the Company Service, our computer systems, or the technical delivery systems of our providers;</li>
              <li>probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures;</li>
              <li>access or search or attempt to access or search the Company Service by any means other than through our currently available, published interfaces that are provided by us, unless you have been specifically allowed to do so in a separate agreement with us;</li>
              <li>forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Company Service to send altered, deceptive or false source-identifying information; or</li>
              <li>disrupt or interfere with the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, mail-bombing the Company Service, or otherwise</li>
              <li>use manual or automated software, devices, or other processes to “crawl,” “scrape,” or “spider” any page of the Company Service. You will not decompile, reverse engineer, or otherwise attempt to obtain the source code of any part of the Company Service.</li>
            </ul>
            <p><b>8.5</b> You further agree that you will not access the Company Service by any means except through the interface provided by Company for access to the Company Service. Creating or maintaining any link from another application to any page at the Company Service without the prior authorization of Company is prohibited. Running or displaying the Company Service, or any information or material displayed via the Company Service in frames or through similar means on another website or application without the prior authorization of Company is prohibited. Any permitted links to the Company Service must comply with all applicable laws, rule and regulations.</p>
            <p><b>8.6</b> Company makes no representation that Materials contained, described or offered via the Company Service are accurate, appropriate or available for use in jurisdictions outside the United States and Canada, or that these Terms of Service comply with the laws of any other country. Visitors who use the Company Service and reside outside the United States do so on their own initiative and are responsible for compliance with all applicable law. You agree that you will not access the Company Service from any territory where its contents are illegal, and that you, and not the Company Parties, are responsible for compliance with applicable law.</p>
            <p><b>8.7</b> Your use of the Company Service is at your own risk, including the risk that you might be exposed to Content that is offensive, indecent, inaccurate, objectionable, or otherwise inappropriate.</p>
            <p><b>8.8</b> Furthermore, you herein agree not to make use of the Services for:</p>
            <ul>
              <li>uploading, posting, emailing, transmitting, or otherwise making available any content that shall be deemed unlawful, harmful, threatening, abusive, harassing, tortious, vulgar, obscene, libelous, or invasive of another's privacy or which is hateful, and/or racially, ethnically, or otherwise objectionable;</li>
              <li>causing harm to minors in any manner whatsoever;</li>
              <li>mpersonating any individual or entity, including, but not limited to, any Company, forum leaders, guides or hosts or falsely stating or otherwise misrepresenting any affiliation with an individual or entity;</li>
              <li>forging captions, headings or titles or otherwise offering any content that you personally have no right to pursuant to any law nor having any contractual or fiduciary relationship with;</li>
              <li> uploading, posting, emailing, transmitting or otherwise offering any such content that may infringe upon any patent, copyright, trademark, or any other proprietary or intellectual rights of any other party;</li>
              <li>uploading, posting, emailing, transmitting or otherwise offering any content that you do not personally have any right to offer pursuant to any law or in accordance with any contractual or fiduciary relationship;</li>
              <li>uploading, posting, emailing, transmitting, or otherwise offering any unsolicited or unauthorized advertising, promotional flyers, "junk mail," "spam," or any other form of solicitation, except in any such areas that may have been designated for such purpose;</li>
              <li>uploading, posting, emailing, transmitting, or otherwise offering any source that may contain a software virus or other computer code, any files and/or programs which have been designed to interfere, destroy and/or limit the operation of any computer software, hardware, or telecommunication equipment;</li>
              <li>disrupting the normal flow of communication, or otherwise acting in any manner that would negatively affect other users' ability to participate in any real-time interactions;</li>
              <li>nterfering with or disrupting any of the Services, servers and/or networks that may be connected or related to our website, including, but not limited to, the use of any software and/or routine to bypass the robot exclusion headers;</li>
              <li>ntentionally or unintentionally violating any local, state, federal, national or international law, including, but not limited to, rules, guidelines, and/or regulations decreed by the Securities and Exchange Commission, in addition to any rules of any nation or other securities exchange, that would include without limitation, the New York Stock Exchange, the American Stock Exchange, or the NASDAQ, and any regulations having the force of law;</li>
              <li>providing informational support or resources, concealing and/or disguising the character, location, and or source to any organization delegated by the United States government as a "foreign terrorist organization" in accordance to Section 219 of the Nationality Act;</li>
              <li>stalking or with the intent to otherwise harass another individual; and/or,</li>
              <li>collecting or storing of any personal data relating to any other user in connection with the prohibited conduct and/or activities which have been set forth in the aforementioned paragraphs.</li>
            </ul>

            <h2>9. Suggestions and Improvements.</h2>
            <p>By sending us any ideas, suggestions, documents or proposals (“Feedback”), you agree that (i) your Feedback does not contain the confidential or proprietary information of third parties, (ii) we are under no obligation of confidentiality, express or implied, with respect to the Feedback, (iii) we may have something similar to the Feedback already under consideration or in development, and (iv) you grant us an irrevocable, non-exclusive, royalty-free, perpetual, worldwide license to use, modify, prepare derivative works, publish, distribute and sublicense the Feedback, and you irrevocably waive, and cause to be waived, against Company and its users any claims and assertions of any moral rights contained in such Feedback.</p>
            <h2>10. Content.</h2>
            <p><b>10.1</b> You shall retain all of your ownership rights in your User Submissions. However, by submitting User Submissions to Company, you hereby grant Company and its affiliates a worldwide, non-exclusive, fully paid-up, royalty-free, perpetual, irrevocable, sublicenseable, and transferable license to use, reproduce, distribute, modify, adapt, prepare derivative works of, display, perform, and otherwise exploit your User Submissions in connection with the Company Service and Company's (and its successor's) business, including without limitation for promoting and redistributing part or all of the Company Service (and derivative works thereof) in any media formats and through any media channels now known or hereafter discovered. You grant Company and its affiliates and sublicensees the right to use the name and/or likeness that you submit in connection with such User Submission if they choose. You also agree to irrevocably waive (and cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Submissions. You also hereby grant to each user of the Company Service a non-exclusive license to access your User Submissions through the Company Service, and to use, reproduce, distribute, prepare derivative works of, display, and perform such User Submissions as permitted by the functionality of the Company Service and this Agreement. By accepting any prize from Company, you hereby grant Company a nonexclusive, perpetual license to print, publish, broadcast and use, worldwide, in any media and at any time, your name, picture, voice, likeness, and/or biographical information for promotional or related purposes without any additional compensation. User Submissions may be copied, published, distributed or otherwise used by Company for any purpose without your permission.</p>
            <p><b>10.2</b> User Submissions Representations and Warranties</p>
            <p>You shall be solely responsible for your own User Submissions and the consequences of posting or publishing them. In connection with User Submissions, you affirm, represent, and/or warrant that: (i) you own, or have the necessary licenses, rights, consents, and permissions to use and authorize Company to use all patent, trademark, copyright, or other proprietary rights in and to any and all User Submissions to enable inclusion and use of User Submissions in the manner contemplated by Company and this Agreement, and to grant the rights and license set forth above, and (ii) your User Submissions, Company's use of such User Submissions pursuant to these Terms of Use, and Company's exercise of the license rights set forth above, do not and will not: (a) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (b) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; or (c) violate any applicable law or regulation.</p>

            <h2>11. Termination.</h2>
            <p>You may terminate your use of the Company Service at any time. You agree that Company may terminate or suspend your access to all or part of the Company Service, with or without notice, in our reasonable discretion, at any time. Company reserves the right to modify or discontinue the Company Service (or any part thereof) with or without notice, at any time. Following the termination or cancellation of your subscription to the Company</p>
            <p>Service and/or your account, we reserve the right to delete all your data in the normal course of operations.</p>

            <h2>12. Purchases and Payments</h2>
            <p><b>12.1</b> Purchase of Services. Your contract for the purchase of Services, if any, is completed once you confirm your purchase and performance of this contract begins as soon as the purchase is complete.</p>
            <p><b>12.2</b> Payment Processing Methods. Company may make available to you various payment processing methods to facilitate the purchase of Services. You must abide by any relevant terms and conditions or other legal agreement with third party payment processors, that governs your use of a given payment processing method. Company may add or remove payment processing methods at its sole discretion and without notice to you. Once your purchase is complete, Company or the payment processor may charge your credit card or other form of payment that you indicate for any Services purchased, along with any additional applicable amounts (including any taxes). You are solely responsible for all amounts payable associated with purchases you make via the Services.</p>

            <p><b>12.3</b> Pricing. Pricing and availability of all Services for sale, if any, displayed through the Site are subject to change at any time before you click the button indicating that you want to purchase such Services.</p>


            <h2>13. Representations.</h2>
            <p>You expressly represent, warrant, and/or acknowledge that:</p>
            <p><b>13.1</b> Company does not warrant or guarantee the suitability or availability of any Material or Content, including without limitation any, data, products or services, found through the Company Service.</p>
            <p><b>13.2</b> Company does not screen the authenticity or quality of any Material or Content or any provider of Material or Content, including, data, products or services found through the Company Service.</p>
            <p><b>13.3</b> Company makes no representations or promises regarding any Material or Content, and that many of the Material or Content provided via the Company Service may be owned or licensed by third parties.</p>
            <p><b>13.4</b> You are of legal age to form a binding contract and are at least eighteen (18) years of age or you have the authority of such legal entity to form a binding contract; all registration information you submit is accurate and truthful; you will maintain the accuracy of such information; and you are legally permitted to use and access the Company Service and take full responsibility for the selection and use of and access to the Company Service.</p>

            <h2>14. Digital Millennium Copyright Act Compliance.</h2>
            <p><b>14.1</b> It is Company's policy to respond to notices of alleged copyright infringement that comply with the Digital Millennium Copyright Act ("DMCA"). Company will promptly terminate without notice any User's access to the Company Service if that User is determined by Company to be a "repeat infringer." A repeat infringer is a User who has been notified by Company of infringing activity violations more than twice and/or who has had a User Submission, or any other user-submitted content removed from the Company Service more than twice.</p>
            <p><b>14.2</b> Procedure for Notifying the Company of Copyright Infringement. Those who believe that their copyrighted work has been infringed or are aware of other infringing material, should contact our Copyright Agent at the address listed below and provide us with the following information:</p>

            <ul>
              <li>An electronic or physical signature of a person authorized to act on behalf of the owner of the copyrighted work that has allegedly been infringed.</li>
              <li>Identification of the copyrighted work claimed to have been infringed.</li>
              <li>Information describing where the allegedly infringing material is located on the Company Service.</li>
              <li>Your address, telephone number, and email address.</li>
              <li>A written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law.</li>
              <li>A statement by you that the above information in your notification is accurate and that, under penalty of perjury, you are the copyright owner or authorized to act on the copyright owner’s behalf. The foregoing information may be emailed or mailed to our Copyright Agent at the addresses listed at the end of this Terms of Service. Following receipt of the information listed above, we will remove or disable access to the infringing material and take reasonable steps to notify the user responsible for posting said material. The posting of infringing copyrighted material may result in the termination of user privileges of such user. If you believe that your copyright has been infringed on the Company Service, please send a "DMCA" compliant notice to <a href="mailto:support@ineedbikeparts.com"></a>support@ineedbikeparts.com.</li>
            </ul>

            <h2>15. Warranties, Disclaimers and Limitations of Liability.</h2>
            <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT:</p>
            <p>YOUR USE OF THE COMPANY SERVICE IS AT YOUR SOLE RISK. THE COMPANY SERVICE AND THE ASSOCIATED MATERIALS AND CONTENT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. EXCEPT AS OTHERWISE EXPRESSLY PROVIDED IN THESE TERMS OF SERVICE, COMPANY, ITS PARENT, SUBSIDIARY AND OTHER AFFILIATED COMPANIES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS AND OTHER REPRESENTATIVES (COLLECTIVELY, THE “COMPANY PARTIES”), EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PURPOSE AND NON-INFRINGEMENT. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, THE COMPANY PARTIES MAKE NO WARRANTY THAT: (I) THE COMPANY SERVICE WILL MEET YOUR REQUIREMENTS; (II) THE COMPANY SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (III) INFORMATION THAT MAY BE OBTAINED VIA THE COMPANY SERVICE WILL BE ACCURATE OR RELIABLE; (IV) THE QUALITY OF ANY AND ALL PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL, INCLUDING ALL MERCHANDISE, GOODS AND SERVICES, OBTAINED OR PURCHASED BY YOU DIRECTLY OR INDIRECTLY THROUGH THE COMPANY SERVICE WILL MEET YOUR EXPECTATIONS OR NEEDS; AND (V) ANY ERRORS IN THE COMPANY SERVICE WILL BE CORRECTED.</p>
            <p>THE COMPANY PARTIES SHALL NOT UNDER ANY CIRCUMSTANCES BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING OUT OF, IN CONNECTION WITH OR RELATING TO THE USE OF OR INABILITY TO USE THE COMPANY SERVICE, INCLUDING ANY LIABILITY: (I) AS A PUBLISHER OF INFORMATION; (II) FOR ANY INCORRECT OR INACCURATE INFORMATION OR ANY ‘BUG’ OF THE COMPANY SERVICE; (III) FOR ANY UNAUTHORIZED ACCESS TO OR DISCLOSURE OF YOUR TRANSMISSIONS OR DATA; (IV) FOR STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON OR VIA THE COMPANY SERVICE; (V) FOR ANY DISPUTES BETWEEN USERS OF THE COMPANY SERVICE OR BETWEEN A USER OF THE COMPANY SERVICE AND A THIRD PARTY; OR (VI) FOR ANY OTHER MATTER RELATING TO THE COMPANY SERVICE OR ANY THIRD PARTY. THIS IS A COMPREHENSIVE LIMITATION OF LIABILITY THAT APPLIES TO ALL DAMAGES OF ANY KIND, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, EVEN IF AN INDIVIDUAL ADVISES THE COMPANY PARTIES OF THE POSSIBILITY OF SUCH DAMAGES. THE LIMITATIONS OF LIABILITY SET FORTH HEREIN ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN COMPANY AND YOU. THE PRODUCTS, INFORMATION AND SERVICES OFFERED ON AND THROUGH THE COMPANY SERVICE WOULD NOT BE PROVIDED TO YOU WITHOUT SUCH LIMITATIONS.</p>
            <p>NOTWITHSTANDING THE FOREGOING, THE SOLE AND ENTIRE MAXIMUM LIABILITY OF THE COMPANY PARTIES FOR ANY REASON, AND YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY CAUSE OR CLAIM WHATSOEVER, SHALL BE LIMITED TO THE CHARGES PAID BY YOU DIRECTLY TO COMPANY VIA THE COMPANY SERVICE FOR SERVICES PROVIDED SOLELY AND DIRECTLY BY COMPANY TO YOU IN THE SIX MONTHS PRIOR TO SUCH CAUSE OR CLAIM.</p>
            <p>SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN TYPES OF DAMAGES. ACCORDINGLY, SOME OF THE ABOVE DISCLAIMERS AND LIMITATIONS MAY NOT APPLY TO YOU.</p>
            <p>If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.”</p>


            <h2>16. Indemnification.</h2>
            <p>You agree to indemnify, defend and hold harmless the Company Parties against all claims, demands, causes of action, losses, expenses, damages and costs (including any reasonable attorneys’ fees), resulting or arising from or relating to your use of the Company Service, any activity related to your account by you or any other person permitted by you, any Content that you submit to, post on or transmit through the Company Service, your breach of these Terms of Service, your infringement or violation of any rights of another, or termination of your access to the Company Service. We reserve the right to assume, at our sole expense, the exclusive defense and control of any such claim or action and all negotiations for settlement or compromise, and you agree to fully cooperate with us in the defense of any such claim, action, settlement or compromise negotiations, as requested by us.</p>

            <h2>17. Notice to California Users.</h2>
            <p>As required by California Code Section 1789.3, this notice is to advise you of the following: a. Company.com is a service provided by I NEED BIKE PARTS.  Braemar Court, Deighton Road, St. Michael, BB 14017. TEL: 1 (800) 266-0373. b. The fees and charges for the Service vary depending on the premium features and tournaments selected by the Account Holder. Company reserves the right to change the amount of any fee or charge and to institute new fees or charges at any time. c. If you have a complaint regarding the Service or desire further information on use of the Service, contact Company by telephone at 1 (800) 266-0373. For complaints, you may also contact the Complaint Assistance Unit of the Division of Consumer Services of the Department of Consumer Affairs in writing at 400 "R" Street, Sacramento, California 95814 or by telephone at 1-916-445-1254.</p>


            <h2>18. Miscellaneous.</h2>
            <p>These Terms of Service constitute the entire agreement between Company and each user of the Company Service with respect to the subject matter of these Terms of Service.</p>
            <ul class="list-letters">
              <li>Entire Agreement; Modification. This Agreement sets forth the entire agreement and understanding of the parties hereto concerning the subject matter hereof. No modification hereof shall be binding upon the parties hereto except by written instrument.</li>
              <li>Invalidity of Particular Provisions. If any term or provision of this Agreement or the application thereof to any person or circumstance shall to any extent be invalid or unenforceable, the other terms of this Agreement, or the application of such terms or provisions to persons or circumstances other than those as to which it is held invalid or unenforceable, shall not be affected thereby, and each term and provision of this Agreement shall be valid and be enforced to the fullest extent permitted by law.</li>
              <li>The failure of the Company to insist upon strict adherence to any term of these Terms of Service shall not constitute a waiver of such term and shall not be considered a waiver or limit that party’s right thereafter to insist upon strict adherence to that term or any other term contained in these Terms of Service. You may not assign your obligations or rights hereunder to another entity or individual. We may transfer, assign or delegate these Terms of Service and its rights and obligations without your consent.</li>
              <li>The terms of this Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Company without restriction. Any assignment attempted to be made in violation of this Agreement shall be void.</li>
              <li>We shall have no liability to you hereunder if we are prevented from or delayed in performing our obligations, or from carrying on our business, by acts, events, omissions or accidents beyond our reasonable control, including, without limitation, strikes, lock-outs or other industrial disputes (whether involving the workforce of us or any other party), failure of a utility service or transport or telecommunications network, act of God, war, riot, civil commotion, malicious damage, compliance with any law or governmental order, rule, regulation or direction, accident, breakdown of plant or machinery, fire, flood or storm.</li>
              <li>No agency, partnership, joint venture, or employment is created as a result of these Terms of Service and you do not have any authority of any kind to bind us in any respect whatsoever.</li>
              <li>No action arising out of these Terms of Service or your use of the Company Service, regardless of form or the basis of the claim, may be brought by you more than one (1) year after the cause of action has arisen (or if multiple causes, from the date the first such cause arose).</li>
            </ul>

            <p>Applicable Law and Jurisdiction. Your use of the Company Service is governed by and will be enforced under the laws of the State of California without regard to its conflict of law provisions. You agree to submit to the personal and exclusive jurisdiction of the courts located within the jurisdiction noted above. You agree that printed copies of any and all agreements and/or notices in electronic form are admissible in any legal or regulatory proceedings. Any controversy, claim, suit, injury or damage arising from or in any way related to the Company Service or these Terms of Service shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association then in effect and before a single arbitrator chosen by Company. Any such controversy, claim, suit, injury or damage shall be arbitrated on an individual basis and shall not be consolidated in any arbitration with any controversy, claim, suit, injury or damage of any other party. Company may seek any interim or preliminary relief from a court of competent jurisdiction in the State listed above necessary to protect its rights pending the completion of arbitration. Each party shall assume its own costs of arbitration. IN ANY CLAIM, ACTION OR PROCEEDING TO ENFORCE ANY RIGHT OR OBLIGATION OF THE PARTIES UNDER THE TERMS OF SERVICE INCLUDING, WITHOUT LIMITATION, RELATING TO YOUR USE OF THE COMPANY SERVICE, YOU HEREBY WAIVE ANY RIGHT YOU MAY NOW HAVE OR HEREAFTER POSSESS TO A TRIAL BY JURY.</p>
            <p>Customer Service. If you have any comments or questions regarding these Terms of Service or wish to report any violation of these Terms of Service, you may contact us at the addresses below. Email Address: support@ineedbikeparts.com</p>

            <p>I Need Bike Parts was designed for, and is intended for use on the desktop mobile web in accordance with the rules and regulations <a href="https://affiliate-program.amazon.com/gp/associates/help/operating/participation/">Associates Program Participation Requirements.</a> I Need Bike Parts is identified as a participant of Amazon’s Associated program, therefore by adding product recommendations to I Need Bike Parts, you are granting I Need Bike Parts and its owners to earn advertising fees from qualifying products made by end users through the Associates Program offered by Amazon.com, Inc. or its affiliates.</p>

            <p>I Need Bike Parts is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.com</p>

            <p>Since 2020 I Need Bike Parts has been handpicking only the best selling, most interesting, most desired, and just plain best products on the web.</p>

            <p>We do not list products solely for a commission. Our goal is to show the best content possible, and if a product happens to have an affiliate program, we'll apply it, but it has no impact on our decision making.</p>

            <p>Affiliate links do not impact your cost as a consumer in anyway. Your cost to purchase goods is the same regardless of our affiliate links.</p>

          </div>
        </Container>
      </Layout>
    </>
  )
}
